/* ============================================================*/
/*   Database name:  BUSUNED                                   */
/*   DBMS name:      Microsoft SQL Server 7.x                  */
/*   Created on:     01/09/2022  01:33 PM                      */
/*   Generada Por:   Ing. Melvin Cascante Morales              */
/* =========================================================== */
USE MASTER
go

Create database BUSUNED
  
go

USE [BUSUNED]
GO
/****** Object:  Table [dbo].[TERMINAL] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TERMINAL](
	[COD_TERMINAL] [numeric](3, 0) NOT NULL,
	[NOM_TERMINAL] [varchar](40) NOT NULL,
	[DIR_TERMINAL] [varchar](40) NOT NULL,
	[NUM_TELEFONO] [varchar](8) NOT NULL,
	[TIM_HORA_APERTURA] [time] NOT NULL,
	[TIM_HORA_CIERRE]   [time] NOT NULL,
	[BOL_ESTADO]   [bit] NOT NULL,
 CONSTRAINT [PK_TERMINAL] PRIMARY KEY CLUSTERED 
(
	[COD_TERMINAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[CONDUCTOR] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CONDUCTOR](
	[NUM_CEDULA] [varchar](15) NOT NULL,
    [NOM_NOMBRE] [varchar](40) NOT NULL,
	[NOM_APELLIDO_1] [varchar](40) NOT NULL,
	[NOM_APELLIDO_2] [varchar](40) NOT NULL,
	[FEC_NACIMIENTO] [date] NOT NULL,
	[TIP_GENERO] [char] NOT NULL,
	[BIT_SUPERVISOR] [bit] NOT NULL,
 CONSTRAINT [PK_CONDUCTOR] PRIMARY KEY CLUSTERED 
(
	[NUM_CEDULA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[AUTOBUS] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AUTOBUS](
	[NUM_IDENTIFICACION] [numeric](4, 0) NOT NULL,
	[NUM_PLACA] [varchar](10) NOT NULL,
	[DSC_MARCA] [varchar](30) NOT NULL,
    [NUM_MODELO] [numeric](4, 0) NOT NULL,
	[NUM_CAPACIDAD] [numeric](3, 0) NOT NULL,
	[BOL_ESTADO] [bit] NOT NULL,
 CONSTRAINT [PK_AUTOBUS] PRIMARY KEY CLUSTERED 
(
	[NUM_IDENTIFICACION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[RUTA] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RUTA](
	[NUM_RUTA] [numeric](4, 0) NOT NULL,
    [COD_TERMINAL_SALIDA] [numeric](3, 0) NOT NULL,
    [COD_TERMINAL_LLEGADA] [numeric](3, 0) NOT NULL,
    [NUM_TARIFA] [numeric](8, 2) NOT NULL,
	[DSC_RUTA] [varchar](40) NOT NULL,
	[NUM_TIPO_RUTA] [numeric](2,0) NOT NULL,
	[BOL_ESTADO] [bit] NOT NULL,
 CONSTRAINT [PK_MESA] PRIMARY KEY CLUSTERED 
(
	[NUM_RUTA] 
 )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


/****** Object:  Table [dbo].[ROL] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ROL](
	[FEC_ROL] [date] NOT NULL,
    [TIM_HORA_SALIDA] [time] NOT NULL,
    [NUM_RUTA] [numeric](4, 0) NOT NULL,
    [NUM_IDENTIFICACION_BUS] [numeric](4, 0) NOT NULL,
	[NUM_CEDULA_CONDUCTOR] [varchar](15) NOT NULL,
 CONSTRAINT [PK_ROL] PRIMARY KEY CLUSTERED 
(
	[FEC_ROL],
    [TIM_HORA_SALIDA],
    [NUM_RUTA],
    [NUM_IDENTIFICACION_BUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[RUTA]  WITH CHECK ADD CONSTRAINT [FK_TERMINAL_RUTA_01] FOREIGN KEY([COD_TERMINAL_SALIDA])
REFERENCES [dbo].[TERMINAL] ([COD_TERMINAL])
GO
ALTER TABLE [dbo].[RUTA] CHECK CONSTRAINT [FK_TERMINAL_RUTA_01]
GO

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[RUTA]  WITH CHECK ADD CONSTRAINT [FK_TERMINAL_RUTA_02] FOREIGN KEY([COD_TERMINAL_LLEGADA])
REFERENCES [dbo].[TERMINAL] ([COD_TERMINAL])
GO
ALTER TABLE [dbo].[RUTA] CHECK CONSTRAINT [FK_TERMINAL_RUTA_02]
GO


SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[ROL]  WITH CHECK ADD CONSTRAINT [FK_ROL_RUTA] FOREIGN KEY([NUM_RUTA])
REFERENCES [dbo].[RUTA] ([NUM_RUTA])
GO
ALTER TABLE [dbo].[ROL] CHECK CONSTRAINT [FK_ROL_RUTA]
GO


GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[ROL]  WITH CHECK ADD CONSTRAINT [FK_ROL_AUTOBUS] FOREIGN KEY([NUM_IDENTIFICACION_BUS])
REFERENCES [dbo].[AUTOBUS] ([NUM_IDENTIFICACION])
GO
ALTER TABLE [dbo].[ROL] CHECK CONSTRAINT [FK_ROL_AUTOBUS]
GO


GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[ROL]  WITH CHECK ADD CONSTRAINT [FK_ROL_CONDUCTOR] FOREIGN KEY([NUM_CEDULA_CONDUCTOR])
REFERENCES [dbo].[CONDUCTOR] ([NUM_CEDULA])
GO
ALTER TABLE [dbo].[ROL] CHECK CONSTRAINT [FK_ROL_CONDUCTOR]
GO


